[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]

[font]
size = 10.5

  [font.bold]
  family = "FairfaxSMHD"
  style = "Bold"

  [font.bold_italic]
  family = "FairfaxSMHD"
  style = "Bold Italic"

  [font.italic]
  family = "FairfaxSMHD"
  style = "Italic"

  [font.normal]
  family = "FairfaxSMHD"
  style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50_000

[window]
opacity = 0.99
